version: 2.1
orbs:
  golang: moorara/golang@0.2.1
jobs:
  build:
    executor:
      dockerhub_password: $DOCKERHUB_PASSWORD
      dockerhub_username: $DOCKERHUB_USERNAME
      name: golang/golang
    steps:
      - checkout
      - golang/install-protoc
      - run:
          name: Compile protos
          command: |
            make compile